[env:esp32-s3-devkitc-1]
platform = espressif32@^6.11.0
board = esp32-s3-devkitc-1
framework = arduino

board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB

upload_port = COM28
monitor_port = COM28
monitor_speed = 115200

build_flags =
    -DBOARD_HAS_PSRAM

lib_deps =
    moononournation/GFX Library for Arduino@1.4.9
    bitbank2/bb_captouch@^1.2.0
    marian-craciunescu/ESP32Ping@^1.7
    adafruit/Adafruit BME280 Library@^2.2.4
    adafruit/Adafruit Unified Sensor@^1.1.14